//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.14 at 05:14:09 PM CDT 
//

package com.innovyt.stop.parse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

	private final static QName _Kml_QNAME = new QName(
			"http://www.opengis.net/kml/2.2", "kml");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.hortonworks.streaming.impl.domain.transport.route.jaxb
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Placemark }
	 * 
	 */
	public Placemark createPlacemark() {
		return new Placemark();
	}

	/**
	 * Create an instance of {@link Document }
	 * 
	 */
	public Document createDocument() {
		return new Document();
	}

	/**
	 * Create an instance of {@link Point }
	 * 
	 */
	public Point createPoint() {
		return new Point();
	}

	/**
	 * Create an instance of {@link Kml }
	 * 
	 */
	public Kml createKml() {
		return new Kml();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Kml }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.opengis.net/kml/2.2", name = "kml")
	public JAXBElement<Kml> createKml(Kml value) {
		return new JAXBElement<Kml>(_Kml_QNAME, Kml.class, null, value);
	}

}
